apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: careers-prod
  name: careers-nodeport
  namespace: careers-prod
spec:
  type: NodePort
  selector:
    app: careers-prod
    type: web
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: https
      port: 443
      targetPort: 8000
