apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: nucleus-prod
  name: nucleus-nodeport
  namespace: nucleus-prod
spec:
  type: NodePort
  selector:
    app: nucleus-prod
    type: cmd
  ports:
    - name: http
      port: 80
      targetPort: 8000
