apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: basket-dev
  name: basket-nodeport
  namespace: basket-dev
spec:
  type: NodePort
  selector:
    app: basket-dev
    type: web
  ports:
    - name: http
      port: 80
      targetPort: 8000

