apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: http_redirector
  name: http_redirector
  namespace: http_redirector
spec:
  type: NodePort
  selector:
    app: http_redirector
  ports:
    - name: http
      port: 80
      targetPort: 80
