apiVersion: v1
kind: Pod
metadata:
  name: metadave-secrets-test-pod
spec:
  containers:
    - name: mdn-sync
      image: quay.io/mozmar/mdn-backup:latest
      volumeMounts:
        - mountPath: "/mdn"
          name: mdn-shared-pvc
      env:
        - name: LOCAL_DIR
          value: /mdn
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mdn-sync-secrets
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mdn-sync-secrets
              key: secret_key
  volumes:
    - name: mdn-shared-pvc
      persistentVolumeClaim:
        claimName: mdn-shared-pvc
  restartPolicy: Never
