apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: block-aws-cron
  namespace: meaocron
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: block-aws-cron
            image: quay.io/mozmar/blockaws:e879510
          restartPolicy: OnFailure
