apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grant-netpol-access
rules:
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "update", "create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grant-netpol-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: meaocron
roleRef:
  kind: ClusterRole
  name: grant-netpol-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: block-aws-cron
  namespace: meaocron
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: block-aws-cron
            image: quay.io/mozmar/blockaws:38f6943
          restartPolicy: OnFailure
