apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: snippets-admin
  name: snippets-nodeport
  namespace: snippets-admin
spec:
  type: NodePort
  selector:
    app: snippets-admin
    type: web
  ports:
    - name: http
      port: 80
      targetPort: 8000
