apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: snippets-prod
  name: snippets-nodeport
  namespace: snippets-prod
spec:
  type: NodePort
  selector:
    app: snippets-prod
    type: web
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: https
      port: 443
      targetPort: 8000

